apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newapi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: devops-tools
  source:
    repoURL: https://github.com/carlosnuezm/k8s-helm.git
    targetRevision: main
    path: k8s/api/myapi
  destination:
    server: https://kubernetes.default.svc
    namespace: newapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true